name: tp-aot-020-nullsafe-chain-class
version: 0.1.0
mode: bin
output: ../../../../build/artifacts/tp-aot-020-nullsafe-chain-class
build-dir: ../../../../build/typephp/tp-aot-020-nullsafe-chain-class
optimize: 0
no-progress: true

sources:
  - main.php
